[package]
name = "threecrate-examples"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "Examples for 3DCrate"
publish = false

[dependencies]
threecrate-core = { path = "../threecrate-core" }
threecrate-gpu = { path = "../threecrate-gpu" }
threecrate-io = { path = "../threecrate-io" }
threecrate-algorithms = { path = "../threecrate-algorithms" }
threecrate-visualization = { path = "../threecrate-visualization" }
anyhow = { workspace = true }
nalgebra = { workspace = true }
tokio = { version = "1.0", features = ["full"] }
rand = { workspace = true }

[[bin]]
name = "basic_usage"
path = "basic_usage.rs"

[[bin]]
name = "gpu_example"
path = "gpu_example.rs"

[[bin]]
name = "comprehensive_gpu_example"
path = "comprehensive_gpu_example.rs"

[[bin]]
name = "interactive_viewer_example"
path = "interactive_viewer_example.rs" 