[package]
name = "threecrate-examples"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "Examples for 3DCrate"
publish = false

[dependencies]
threecrate-core = { path = "../threecrate-core" }
threecrate-io = { path = "../threecrate-io" }
anyhow = { workspace = true }

[[bin]]
name = "basic_usage"
path = "basic_usage.rs" 