[package]
name = "threecrate-reconstruction"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
description = "Surface reconstruction algorithms for 3DCrate"

[dependencies]
threecrate-core = { path = "../threecrate-core" }
threecrate-algorithms = { path = "../threecrate-algorithms" }
nalgebra = { workspace = true }
ndarray = { workspace = true }
rayon = { workspace = true }
itertools = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
approx = { workspace = true } 